[package]
name = "hello_wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "load_wasm_module"
test = false
bench = false


[dependencies]
wasmer = "2.3.0"
anyhow = "1.0.62"
